import { Platform, StyleSheet } from 'react-native';
import { responsiveSize, screenDimensions } from '../utils/responsiveUtils';

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  videoContainer: {
    flex: 1,
    position: 'relative',
  },
  mainVideoContainer: {
    flex: 1,
    borderRadius: responsiveSize(24),
    overflow: 'hidden',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: responsiveSize(12) },
    shadowOpacity: 0.4,
    shadowRadius: responsiveSize(24),
    elevation: 15,
  },
  mainVideo: {
    flex: 1,
    borderRadius: responsiveSize(12),
    position: 'relative',
  },
  videoFrame: {
    flex: 1,
    position: 'relative',
  },
  videoBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: screenDimensions.height * 0.6,
  },
  interestsContainer: {
    position: 'absolute',
    bottom: responsiveSize(320),
    left: responsiveSize(10),
    right: responsiveSize(10),
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: responsiveSize(8),
  },
  interestTag: {
    paddingHorizontal: responsiveSize(16),
    paddingVertical: responsiveSize(8),
    borderRadius: responsiveSize(20),
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  interestText: {
    color: '#fff',
    fontSize: responsiveSize(12),
    fontWeight: '500',
  },
  audioIndicator: {
    position: 'absolute',
    bottom: responsiveSize(screenDimensions.height * 0.42),
    right: responsiveSize(24),
    flexDirection: 'row',
    alignItems: 'center',
    gap: responsiveSize(8),
    paddingHorizontal: responsiveSize(20),
    paddingVertical: responsiveSize(14),
    borderRadius: responsiveSize(30),
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  audioWaves: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: responsiveSize(3),
  },
  audioWave: {
    width: responsiveSize(2.5),
    backgroundColor: '#fff',
    borderRadius: responsiveSize(1.5),
    opacity: 0.8,
  },
  swipeHint: {
    position: 'absolute',
    bottom: responsiveSize(120),
    right: responsiveSize(24),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: responsiveSize(16),
    paddingVertical: responsiveSize(8),
    borderRadius: responsiveSize(20),
    gap: responsiveSize(8),
  },
  swipeHintText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: responsiveSize(12),
    fontWeight: '500',
  },
  nextUserPreview: {
    position: 'absolute',
    bottom: responsiveSize(screenDimensions.height * (Platform.OS === 'ios' ? 0.39 : 0.42)),
    left: responsiveSize(10),
    width: responsiveSize(200),
    height: responsiveSize(45),
  },
  nextUserCard: {
    flex: 1,
    padding: responsiveSize(12),
    borderRadius: responsiveSize(12),
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'hidden',
    gap: responsiveSize(8),
  },
  nextUserAvatar: {
    width: responsiveSize(28),
    height: responsiveSize(28),
    borderRadius: responsiveSize(8),
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextUserInfoContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    gap: responsiveSize(1),
  },
  nextUserAvatarText: {
    color: '#333',
    fontSize: responsiveSize(12),
    fontWeight: '700',
  },
  nextUserName: {
    color: '#fff',
    fontSize: responsiveSize(12),
    fontWeight: '600',
  },
  nextUserInfo: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: responsiveSize(9),
  },
  // Connection status overlay
  connectionOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: responsiveSize(150),
    backgroundColor: 'rgba(0,0,0,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  connectionText: {
    color: '#fff',
    fontSize: responsiveSize(14),
    fontWeight: '600',
    marginTop: responsiveSize(12),
    textAlign: 'center',
  },
});
